/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Jobs
         * @description Search jobs across Adzuna and JSearch, deduplicated and paginated.
         */
        get: operations["search_jobs_v1_jobs__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Fetch a single job listing by ID.
         */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Jobs */
        get: operations["list_saved_jobs_v1_saved_jobs__get"];
        put?: never;
        /** Save Job */
        post: operations["save_job_v1_saved_jobs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-jobs/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Manual Job
         * @description Add a job found on an external site by URL + details (FR-004a).
         */
        post: operations["save_manual_job_v1_saved_jobs_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-jobs/{saved_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Saved Job */
        delete: operations["delete_saved_job_v1_saved_jobs__saved_job_id__delete"];
        options?: never;
        head?: never;
        /** Update Saved Job */
        patch: operations["update_saved_job_v1_saved_jobs__saved_job_id__patch"];
        trace?: never;
    };
    "/v1/saved-searches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Searches */
        get: operations["list_saved_searches_v1_saved_searches__get"];
        put?: never;
        /** Create Saved Search */
        post: operations["create_saved_search_v1_saved_searches__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-searches/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get New Matches
         * @description Jobs found since each saved search was last viewed.
         */
        get: operations["get_new_matches_v1_saved_searches_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-searches/mark-seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Matches Seen */
        post: operations["mark_matches_seen_v1_saved_searches_mark_seen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Saved Search */
        delete: operations["delete_saved_search_v1_saved_searches__search_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collections */
        get: operations["list_collections_v1_collections__get"];
        put?: never;
        /** Create Collection */
        post: operations["create_collection_v1_collections__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection */
        get: operations["get_collection_v1_collections__collection_id__get"];
        put?: never;
        post?: never;
        /** Delete Collection */
        delete: operations["delete_collection_v1_collections__collection_id__delete"];
        options?: never;
        head?: never;
        /** Update Collection */
        patch: operations["update_collection_v1_collections__collection_id__patch"];
        trace?: never;
    };
    "/v1/pipeline-stages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stages */
        get: operations["list_stages_v1_pipeline_stages__get"];
        put?: never;
        /** Create Stage */
        post: operations["create_stage_v1_pipeline_stages__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipeline-stages/{stage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Stage */
        delete: operations["delete_stage_v1_pipeline_stages__stage_id__delete"];
        options?: never;
        head?: never;
        /** Update Stage */
        patch: operations["update_stage_v1_pipeline_stages__stage_id__patch"];
        trace?: never;
    };
    "/v1/pipeline-stages/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Job
         * @description Move a saved job to a different Kanban column.
         */
        post: operations["move_job_v1_pipeline_stages_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_v1_ai_resumes_get"];
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_v1_ai_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Document */
        post: operations["generate_document_v1_ai_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_v1_ai_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Document */
        patch: operations["update_document_v1_ai_documents__doc_id__patch"];
        trace?: never;
    };
    "/v1/ai/documents/{doc_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Document Pdf
         * @description Render the latest content as PDF using weasyprint.
         */
        get: operations["download_document_pdf_v1_ai_documents__doc_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_v1_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Delete the current user account (FR-020).
         *
         *     The account is deactivated immediately; all owned rows and stored
         *     files are permanently purged after a 30-day grace period by the
         *     daily `purge_deleted_users` job (cascade via FK).
         */
        delete: operations["delete_account_v1_users_me_delete"];
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_v1_users_me_patch"];
        trace?: never;
    };
    "/v1/users/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Data
         * @description Serialize all user-owned data as a JSON download.
         */
        get: operations["export_data_v1_users_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_v1_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics Summary */
        get: operations["get_analytics_summary_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsSummary */
        AnalyticsSummary: {
            /** Total Saved */
            total_saved: number;
            /** Total Applied */
            total_applied: number;
            /** Total Interviews */
            total_interviews: number;
            /** Response Rate */
            response_rate: number;
            /** Weekly Activity */
            weekly_activity: components["schemas"]["WeeklyActivity"][];
        };
        /** Body_move_job_v1_pipeline_stages_move_post */
        Body_move_job_v1_pipeline_stages_move_post: {
            /**
             * Saved Job Id
             * Format: uuid
             */
            saved_job_id: string;
            /** Stage Id */
            stage_id?: string | null;
        };
        /** Body_upload_resume_v1_ai_resumes_post */
        Body_upload_resume_v1_ai_resumes_post: {
            /** File */
            file: string;
        };
        /** CollectionCreate */
        CollectionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
        };
        /** CollectionSchema */
        CollectionSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Color */
            color: string | null;
            /** Sort Order */
            sort_order: number;
            /** Is Default */
            is_default: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CollectionUpdate */
        CollectionUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
        };
        /** DailySignup */
        DailySignup: {
            /** Date */
            date: string;
            /** Count */
            count: number;
        };
        /** GeneratedDocumentCreate */
        GeneratedDocumentCreate: {
            /** Job Listing Id */
            job_listing_id?: string | null;
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "resume" | "cover_letter";
        };
        /** GeneratedDocumentSchema */
        GeneratedDocumentSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Job Listing Id */
            job_listing_id: string | null;
            /** Resume Id */
            resume_id: string | null;
            /** Document Type */
            document_type: string;
            /** Content */
            content: string;
            /** Edited Content */
            edited_content: string | null;
            /** Model Used */
            model_used: string | null;
            /** Generation Ms */
            generation_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GeneratedDocumentUpdate */
        GeneratedDocumentUpdate: {
            /** Edited Content */
            edited_content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobListingSchema */
        JobListingSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External Id */
            external_id: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Is Remote */
            is_remote: boolean;
            /** Description */
            description: string | null;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Currency */
            currency: string | null;
            /** Job Type */
            job_type: string | null;
            /** Apply Url */
            apply_url: string;
            /** Posted At */
            posted_at: string | null;
            /** Is Expired */
            is_expired: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** JobSearchResponse */
        JobSearchResponse: {
            /** Results */
            results: components["schemas"]["JobListingSchema"][];
            meta: components["schemas"]["PaginatedMeta"];
        };
        /**
         * ManualJobCreate
         * @description A job the user found on an external site (FR-004a).
         */
        ManualJobCreate: {
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /**
             * Location
             * @default Not specified
             */
            location: string;
            /**
             * Is Remote
             * @default false
             */
            is_remote: boolean;
            /** Collection Id */
            collection_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** NewMatchesResponse */
        NewMatchesResponse: {
            /** Matches */
            matches: components["schemas"]["SearchMatches"][];
            /** Total New */
            total_new: number;
        };
        /** PaginatedMeta */
        PaginatedMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PipelineStageCreate */
        PipelineStageCreate: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** PipelineStageSchema */
        PipelineStageSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
            /** Color */
            color: string | null;
            /** Is Default */
            is_default: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PipelineStageUpdate */
        PipelineStageUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** PlatformStats */
        PlatformStats: {
            /** Total Users */
            total_users: number;
            /** Active 7D */
            active_7d: number;
            /** Active 30D */
            active_30d: number;
            /** New 7D */
            new_7d: number;
            /** Signups By Day */
            signups_by_day: components["schemas"]["DailySignup"][];
        };
        /** ResumeSchema */
        ResumeSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SavedJobCreate */
        SavedJobCreate: {
            /**
             * Job Listing Id
             * Format: uuid
             */
            job_listing_id: string;
            /** Collection Id */
            collection_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SavedJobSchema */
        SavedJobSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Job Listing Id
             * Format: uuid
             */
            job_listing_id: string;
            /** Collection Id */
            collection_id: string | null;
            /** Pipeline Stage Id */
            pipeline_stage_id: string | null;
            /** Notes */
            notes: string | null;
            /** Applied At */
            applied_at: string | null;
            /**
             * Last Stage Change
             * Format: date-time
             */
            last_stage_change: string;
            /** Is Archived */
            is_archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            job_listing: components["schemas"]["JobListingSchema"];
        };
        /** SavedJobUpdate */
        SavedJobUpdate: {
            /** Collection Id */
            collection_id?: string | null;
            /** Pipeline Stage Id */
            pipeline_stage_id?: string | null;
            /** Notes */
            notes?: string | null;
            /** Applied At */
            applied_at?: string | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /** SavedSearchCreate */
        SavedSearchCreate: {
            /** Q */
            q: string;
            /** Location */
            location?: string | null;
            /**
             * Remote Only
             * @default false
             */
            remote_only: boolean;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Experience */
            experience?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Name */
            name?: string | null;
        };
        /** SavedSearchSchema */
        SavedSearchSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Q */
            q: string;
            /** Location */
            location: string | null;
            /** Remote Only */
            remote_only: boolean;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Experience */
            experience: string | null;
            /** Job Type */
            job_type: string | null;
            /** Is Active */
            is_active: boolean;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Viewed At */
            last_viewed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchMatches */
        SearchMatches: {
            search: components["schemas"]["SavedSearchSchema"];
            /** New Jobs */
            new_jobs: components["schemas"]["JobListingSchema"][];
            /** New Count */
            new_count: number;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Detail */
            detail?: string | null;
        };
        /** UserProfile */
        UserProfile: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Image */
            image?: string | null;
            /** Role */
            role: string;
            /** Follow Up Days */
            follow_up_days: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Follow Up Days */
            follow_up_days?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyActivity */
        WeeklyActivity: {
            /** Week Start */
            week_start: string;
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_jobs_v1_jobs__get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                location?: string | null;
                remote_only?: boolean;
                salary_min?: number | null;
                salary_max?: number | null;
                experience?: string | null;
                job_type?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_jobs_v1_saved_jobs__get: {
        parameters: {
            query?: {
                collection_id?: string | null;
                pipeline_stage_id?: string | null;
                is_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_job_v1_saved_jobs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_manual_job_v1_saved_jobs_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_job_v1_saved_jobs__saved_job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                saved_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_saved_job_v1_saved_jobs__saved_job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                saved_job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedJobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_searches_v1_saved_searches__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"][];
                };
            };
        };
    };
    create_saved_search_v1_saved_searches__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_new_matches_v1_saved_searches_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewMatchesResponse"];
                };
            };
        };
    };
    mark_matches_seen_v1_saved_searches_mark_seen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_saved_search_v1_saved_searches__search_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_v1_collections__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSchema"][];
                };
            };
        };
    };
    create_collection_v1_collections__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_v1_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_v1_collections__collection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_collection_v1_collections__collection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stages_v1_pipeline_stages__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStageSchema"][];
                };
            };
        };
    };
    create_stage_v1_pipeline_stages__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineStageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stage_v1_pipeline_stages__stage_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stage_v1_pipeline_stages__stage_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineStageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_job_v1_pipeline_stages_move_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_move_job_v1_pipeline_stages_move_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_v1_ai_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeSchema"][];
                };
            };
        };
    };
    upload_resume_v1_ai_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_v1_ai_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_document_v1_ai_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratedDocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_ai_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_v1_ai_documents__doc_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratedDocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_document_pdf_v1_ai_documents__doc_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    delete_account_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_profile_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_data_v1_users_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stats_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStats"];
                };
            };
        };
    };
    get_health_v1_admin_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"][];
                };
            };
        };
    };
    list_users_v1_admin_users_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_summary_v1_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
        };
    };
}
