"""sync schema with current models

Revision ID: 6d32186f6f5a
Revises: 0002
Create Date: 2026-07-29 17:49:40.113247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d32186f6f5a'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('collections', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('collections', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('collections', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_collections_user_name'), 'collections', type_='unique')
    op.create_unique_constraint('uq_collection_user_name', 'collections', ['user_id', 'name'])
    op.add_column('pipeline_stages', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.alter_column('pipeline_stages', 'color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_pipeline_stages_user_name'), 'pipeline_stages', type_='unique')
    op.create_unique_constraint('uq_stage_user_name', 'pipeline_stages', ['user_id', 'name'])
    op.drop_column('pipeline_stages', 'position')
    op.add_column('saved_jobs', sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('saved_jobs', sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('saved_jobs', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('saved_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('saved_jobs', 'last_stage_change',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_saved_jobs_pipeline'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_constraint(op.f('uq_saved_jobs_user_job'), 'saved_jobs', type_='unique')
    op.create_index('ix_saved_jobs_last_stage_change', 'saved_jobs', ['last_stage_change'], unique=False)
    op.create_index('ix_saved_jobs_user_collection', 'saved_jobs', ['user_id', 'collection_id'], unique=False)
    op.create_index('ix_saved_jobs_user_stage', 'saved_jobs', ['user_id', 'pipeline_stage_id'], unique=False)
    op.create_unique_constraint('uq_saved_job_user_listing', 'saved_jobs', ['user_id', 'job_listing_id'])
    op.drop_constraint(op.f('saved_jobs_job_listing_id_fkey'), 'saved_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'saved_jobs', 'job_listings', ['job_listing_id'], ['id'])
    op.add_column('users', sa.Column('image', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'image')
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('saved_jobs_job_listing_id_fkey'), 'saved_jobs', 'job_listings', ['job_listing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_saved_job_user_listing', 'saved_jobs', type_='unique')
    op.drop_index('ix_saved_jobs_user_stage', table_name='saved_jobs')
    op.drop_index('ix_saved_jobs_user_collection', table_name='saved_jobs')
    op.drop_index('ix_saved_jobs_last_stage_change', table_name='saved_jobs')
    op.create_unique_constraint(op.f('uq_saved_jobs_user_job'), 'saved_jobs', ['user_id', 'job_listing_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_pipeline'), 'saved_jobs', ['user_id', 'pipeline_stage_id'], unique=False)
    op.alter_column('saved_jobs', 'last_stage_change',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('saved_jobs', 'updated_at')
    op.drop_column('saved_jobs', 'is_archived')
    op.drop_column('saved_jobs', 'follow_up_sent_at')
    op.drop_column('saved_jobs', 'applied_at')
    op.add_column('pipeline_stages', sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_stage_user_name', 'pipeline_stages', type_='unique')
    op.create_unique_constraint(op.f('uq_pipeline_stages_user_name'), 'pipeline_stages', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('pipeline_stages', 'color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('pipeline_stages', 'sort_order')
    op.drop_constraint('uq_collection_user_name', 'collections', type_='unique')
    op.create_unique_constraint(op.f('uq_collections_user_name'), 'collections', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('collections', 'updated_at')
    op.drop_column('collections', 'sort_order')
    op.drop_column('collections', 'color')
    op.drop_column('collections', 'description')
    # ### end Alembic commands ###
